### ISSUE TITLE
the include command causes an error

### ISSUE THREAD

**Issue by dvhwgumby** [puppetlabs/cpp-hocon#98]
Hi folks,

If I try to parse a .conf file with an include directive I get the error ```Error: reader() should not be called on resources```

I am calling   ```hocon::program_options::parse_file(filename, reasoner_options, true);```

I'm running on MacOS.

Also I'm not sure how to specify the search directories for "include" though at the moment we have a single flat directory so this doesn't matter.

**Comment by MikaelSmith** [comment]
That's strange, what does your `include` directive look like?

I think there are some pretty strict limitations on it right now, but I've definitely used it for something like `include file("/absolute/path")`.

**Comment by luben** [comment]
I think you are hitting #94

**Comment by luben** [comment]
BTW, as I see some people commenting, is this project maintained? I sent a PR for fixing another bug with included files (#95) without any reaction for more than 3 months. @dvhwgumby , sorry for the noise,

**Comment by dvhwgumby** [comment]
Hmm. The lightbend parser says it wants ```include “foo”``` — and it can be used inside an object (though that’s way more sophisticated than we need)!  

I tried your suggested syntax and our java code (using the lightbend parser) rejected it.   We verified this in the head of the GitHub config repo

So, support for ```include “foo”``` would help a lot. 

As far as directories: I’m perfectly happy to change directories in my code to manage them.   That is painless now I know it’s the mechanism. 

Thanks for building this package btw — it has already saved my bacon. Took me less than a day to integrate (using factor and pxp as examples as well as the source) — and most of that time was figuring out the include issue.

**Comment by dvhwgumby** [comment]
FWIW, the "spec" for HOCON (https://github.com/lightbend/config/blob/master/HOCON.md#includes) considers the syntax our team used to be legit.

**Comment by MikaelSmith** [comment]
Understood. This is currently an incomplete implementation of the spec. It would be nice to improve it, but I'm not personally spending a ton of time on it.

I'm surprised the lightbend parser rejected `include file("foo")`, since they claim to support it in https://github.com/lightbend/config#features-of-hocon.

**Comment by MikaelSmith** [comment]
I can give some suggestions of where to look to start a fix. Our code mirrors the lightbend/config implementation fairly closely, so you can use that to compare where we might be missing some implementation.

The parser is in src/config_document_parser.cc. `parse_context::parse_include` is the first place I'd look, which at least accepts `include "foo"`. It's possible we're setting that up with the wrong type, but I suspect the actual problem is later. It's possible `parse_context::parse_include` in src/config_parser.cc is a problem.

If `b.conf` is empty, do you get an error? Possible the parser for the included file is not setup correctly.

**Comment by SeaTalk** [comment]
In my case, I fix it by changing some code. And my change exists [here](https://github.com/SeaTalk/cpp-hocon) . For now, it works fine for me. I want you guys review my code and find out where bugs may lay. 
Thanks a lot ~

**Comment by MikaelSmith** [comment]
Thanks for providing that! Not sure when someone might get to looking at it. If anyone's interested in turning that into a PR, I can try to help review it.

**Comment by MikaelSmith** [comment]
I believe this is fixed by https://github.com/puppetlabs/cpp-hocon/pull/115. Please re-open the issue if I'm mistaken.
